# Numpy 배열 자르고 붙이기
- 상황에 따라 배열의 특정 성분을 뽑아 벡터로 사용하거나 붙여서 새로운 벡터를 만들기도 함

### Numpy 배열을 자르고 붙이기 위해 필요한 함수/라이브러리
- `np.reshaep(a, (m,n))`: `a`를 mxn 배열로 변환. 괄호 안의 값을 변경하여 다양한 형태로 배열을 변환
- `np.c_[a,b]`: 배열 `a`에 배열 `b`의 column들을 추가
- `np.r_[a,b]`: 배열 `a`에 배열 `b`의 row들을 추가
- `np.concatenate((a,b), axiz=n)`: 배열 `a`에 n+1차원 방향으로 배열 `b`를 추가
  - n=0 : row 추가
  - n=1 : column 추가

### 실습
1. 배열 `a`를 `reshape`을 사용하여 (3,3)배열로 변환
2. 변환된 배열 `array1`의 2번째 column을 구함. (3,1) 형태로 `array2`에 저장
3. `array1`에 column방향으로 `array2`를 붙임
4. `array3`를 (3,2,2) 배열로 변환
5. `array4`의 3개의 (2,2)행렬 중 첫 번째 행렬을 구함

In [1]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9])

# 배열 x를 reshape를 사용하여 (3,3) 배열로 변환해봅시다.
array1 = np.reshape(x, (3,3))
print("(3x3) 배열 x:\n", array1)

# 변환된 배열 array1의 2번째 column을 구해봅니다. 
# (3, 1) 형태로 array2에 저장합니다.
array2 = array1[:,1].reshape((3,1))
print("\narray1의 2번째 column :\n", array2)

# array1에 column 방향으로 array2를 붙여봅니다.
array3 = np.c_[array1, array2]
print("\narray1에 column 방향으로 array2 붙이기:\n", array3)

# array3을 reshape를 사용하여 (3,2,2) 배열로 변환해봅시다.
array4 = np.reshape(array3, (3,2,2))
print("\n(3,2,2) array4:\n", array4)

# array4의 3개의 (2,2)행렬 중 첫 번째 행렬을 구합니다.
array5 = array4[0,:,:]
print("\narray4의 3개의 (2,2)행렬 중 첫 번째 행렬:\n", array5)

(3x3) 배열 x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array1의 2번째 column :
 [[2]
 [5]
 [8]]

array1에 column 방향으로 array2 붙이기:
 [[1 2 3 2]
 [4 5 6 5]
 [7 8 9 8]]

(3,2,2) array4:
 [[[1 2]
  [3 2]]

 [[4 5]
  [6 5]]

 [[7 8]
  [9 8]]]

array4의 3개의 (2,2)행렬 중 첫 번째 행렬:
 [[1 2]
 [3 2]]
