# Numpy 배열로 사칙연산하기
- Numpy로 선언한 배열은 기본적인 사칙 연산 가능

### Numpy 배열을 사칙연산하기 위한 함수/라이브러리
- `a+b`: 배열 `a`,`b`의 같은 위치 성분끼리 덧셈을 해줌
- `a-b`: 배열 `a`,`b`의 같은 위치 성분끼리 뺄셈을 해줌
- `a*b`: 배열 `a`,`b`의 같은 위치 성분끼리 곱셈을 해줌
- `a/b`: 배열 `a`의 각 성분의 배열 `b`의 같은 위치의 성분으로 나눗셈을 해줌

### 실습
1. `array1`의 첫 번째 column벡터와 두 번째 column 벡터를 더하기
2. `aaray1`의 첫 번째 row벡터와 두 번째 `row` 벡터를 빼기
3. `array2`와 `array3`을 곱하기
4. `array1`을 `array5`로 나누기

In [2]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# array1 첫 번째 column 벡터와 두 번째 column 벡터를 더하여 봅시다.
array2 = array1[:,0] + array1[:,1]
print("1st column of array1 + 2nd column of array1:\n", array2)

# array1 첫 번째 row 벡터와 두 번째 row 벡터를 빼 봅시다.
array3 = array1[0,:] - array1[1,:]
print("\n1st row of array1 - 2nd row of array1:\n", array3)

# array2과 array3을 곱하여 봅시다.
array4 = array2 * array3
print("\narray2 * array3:\n", array4)

array5 = np.c_[array2,array3,array4]

# array1을 array5로 나누어 봅시다.
array6 = array1 / array5
print("\narray1 / array5:\n", array6)

1st column of array1 + 2nd column of array1:
 [ 3  9 15]

1st row of array1 - 2nd row of array1:
 [-3 -3 -3]

array2 * array3:
 [ -9 -27 -45]

array1 / array5:
 [[ 0.33333333 -0.66666667 -0.33333333]
 [ 0.44444444 -1.66666667 -0.22222222]
 [ 0.46666667 -2.66666667 -0.2       ]]
