# Numpy 배열 선언하기
- Numpy는 배열(array)의 수학적 계산을 위한 파이썬 기반 라이브러리

### Numpy 배열을 선언하기 위한 함수/라이브러리
- `np.array(list)`: `list`를 Numpy배열로 선언
- `np.zeros(shape)`: 모든 값이 0인 `shape`모양의 배열 선언
- `np.ones(shape)`: 모든 값이 1인 `shape`모양의 배열 선언
- `np.random.random(shape)`: 0이상 1미만의 랜덤값을 갖는 `shape`모양의 배열을 선언
- `np.arange(start, stop, step)`: `start`부터 `stop`전까지 `step`만큼의 크기로 증가하는 배열을 선언

### 실습
1. 리스트 x를 numpy 배열로 저장
2. 모든 원소가 0인 3x3의 배열을 저장
3. 모든 원소가 1인 2x5의 배열을 저장
4. 0이상 1미만의 랜덤 값을 갖는 5x3의 배열을 저장
5. 0부터 9까지의 값을 원소로 하는 1x10 배열을 저장


In [1]:
import numpy as np

x=[[1,2,3], [4,5,6], [7,8,9]]

def solution(data):
    #리스트 x를 Numpy 배열로 출력합니다.
    array1 = np.array(x)

    #모든 원소가 0인 3×3의 배열을 출력합니다.
    array2 = np.zeros((3,3))

    #모든 원소가 1인 2×5의 배열을 출력합니다.
    array3 = np.ones((2,5))

    # 0 이상 1 미만의 랜덤 값을 갖는 5×3의 배열을 출력합니다.
    array4 = np.random.random((5,3))    

    # 0부터 9까지의 값을 원소로 하는 1×10 배열을 출력합니다.
    array5 = np.arange(10)
    
    return array1, array2, array3, array4, array5

def print_answer(**kwargs):
    for key in kwargs.keys():
        print(key,":", kwargs[key])

array1, array2, array3, array4, array5 = solution(x)

print_answer(array1=array1, array2=array2, array3=array3, array4=array4, array5=array5)

array1 : [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2 : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array3 : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
array4 : [[0.44651088 0.85517588 0.10616766]
 [0.77515296 0.95634739 0.86565421]
 [0.08453741 0.05291691 0.75138034]
 [0.31023349 0.08555535 0.54051125]
 [0.38046414 0.11728303 0.90607265]]
array5 : [0 1 2 3 4 5 6 7 8 9]
