## [이론1] Numpy 라이브러리
- 방대한 양의 데이터를 처리하고, 머신러닝에 사용되는 수식을 계산하기 위해서는 **배열(array)**을 사용해야 함
- 행렬 데이터에 대한 계산을 python에서 가장 잘 수행해 줄 수 있는 라이브러리가 **numpy**
- numpy에서는 기본적으로 배열을 행렬로 생각하고, 그 행렬 계산을 쉽게 하도록 도와줌

### python 배열
- python에서 배열 덧셈은 아래와 같은 결과를 보여줌

In [ ]:
a = [1, 2, 3, 4, 5]  # 1차원 벡터
b = [1, 1, 1, 1, 1]

a+b

[1, 2, 3, 4, 5, 1, 1, 1, 1, 1]


### 0. 라이브러리 import 하기
- import 할 때는 주로 `np`라는 명칭을 사용

In [2]:
import numpy as np

### 1. Numpy 배열 선언하기
##### numpy 자료형 선언
- `array()`는 파이썬의 리스트를 numpy의 배열 자료형으로 변환하는 함수


In [ ]:
a = np.array([0, 1, 2, 3]) # numPy 배열 초기화
a

array([0, 1, 2, 3])

##### arange 함수
- `arange(start, stop, step)`함수는 **start**부터 **stop**전까지 **step**만큼의 크기로 증가하는 배열 선언

In [ ]:
b = np.arange(1,8,2) # 범위(1~8), 2씩 증가
b

- 인자가 1개인 경우 **start = 0, step = 1**로 default 설정

In [ ]:
# 범위 (0~10) 
b = np.arange(10) 
b

- 인자가 2개인 경우 **step = 1**으로 default 설정

In [ ]:
b = np.arange(1,4) # 범위(1~4)
b

##### zeros, ones, random 함수
- `zeros()`는 선언하고 싶은 배열의 크기를 입력하여 0으로 채워진 배열을 선언

In [ ]:
np.zeros((3,2)) # (3,2) 크기 0 행렬

- `ones`는 선언하고 싶은 배열의 크기를 입력하여 1로 채워진 배열을 선언

In [ ]:
np.ones((3,4)) # (3,4) 크기의 1 행렬

`random()`은 선언하고 싶은 배열의 크기를 입력하여 0 이상 1 미만의 랜덤 값을 갖는 배열을 선언

In [ ]:
np.random.random((2,3)) # (2,3) 크기의 랜덤 행렬

### 2. 배열 정보 확인하기
##### shape, size
- 배열의 크기를 `.shape`과 `.size`를 통하여 확인
- `.shape`은 배열의 row와 column의 크기를 출력
- `.size`는 배열의 성분들 총 개수를 출력


In [3]:
c = np.array([[1,2,3],[4,5,6]])
c.shape

(2, 3)

In [4]:
c.size

6

##### dtype
- 배열의 성분들 타입을 알기 위함

In [5]:
c.dtype

dtype('int64')

##### 성분 확인
- 배열의 인덱스를 사용하여 해당 성분을 확인

In [6]:
c[0,0]

1

In [7]:
c[1,2]

6

- 배열의 인덱스는 0부터 시작

### 3. 배열의 형태 변경하기
##### reshape
- `reshape`은 배열의 형태를 변경


In [8]:
a = np.array([1,2,3,4])
a = a.reshape((2, 2)) # 원래 a의 size와 변경할 a의 size는 같아야 함
# a = np.reshape(a,(2,2)) # 이와 같은 방법으로도 사용 가능
a

array([[1, 2],
       [3, 4]])

- 변경될 배열의 `shape`과 `size`를 확인

In [9]:
a.shape

(2, 2)

In [10]:
a.size

4

- 이전에 (4,)였던 배열의 shape이 (2,2)로 변경
- 개수를 변경한 것은 아니기 때문에 size는 동일한 결과
- row의 개수와 상관없이 column의 수를 고정하고 싶다면 row 크기를 입력하는 인자에 -1을 입력

In [11]:
a_col = a.reshape((-1,1))
a_col

array([[1],
       [2],
       [3],
       [4]])

In [12]:
a_col.shape

(4, 1)

- 반대로 row를 고정해야 한다면 column입력에 -1을 설정

In [13]:
a_row = a_col.reshape((2,-1))
a_row

array([[1, 2],
       [3, 4]])

In [14]:
a_row.shape

(2, 2)


### 4. 배열 자르고 붙이기
##### 배열 자르기
-  배열의 인덱스 정보를 활용하여 자름

In [15]:
a = np.array([[1,2,3],[4,5,6]]) # (2,3) 크기의 행렬 a 선언
a

array([[1, 2, 3],
       [4, 5, 6]])

- 원래 행렬에서의 column벡터를 뽑고 싶을 때 row 인덱스를 입력하는 부분에는 `:`, column 인덱스를 입력하는 부분에는 해당 column 인덱스를 입력

In [16]:
a[:,0] # column 벡터로 자르기

array([1, 4])

In [17]:
a[:,-1] # 마지막 column 벡터로 자르기

array([3, 6])

- 원래 행렬에서의 row 벡터를 뽑고 싶을 때 column 인덱스를 입력하는 부분에는 :, row 인덱스를 입력하는 부분에는 해당 row 인덱스를 입력

In [18]:
a[1,:] # row 벡터로 자르기

array([4, 5, 6])

In [19]:
a[-1,:] # 마지막 row 벡터로 자르기

array([4, 5, 6])

- `배열[시작값:도착값,간격]`을 이용하여 배열의 일부를 잘라 표시 가능

In [20]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) # (2,6) 크기의 행렬 a 선언
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

- `배열[시작값:]`은 시작값 인덱스를 시작으로 배열의 마지막 인덱스까지의 배열을 표시

In [21]:
a[:,4:]

array([[ 5,  6],
       [11, 12]])

- 도착값은 마지막 인덱스 값보다 1이 큼
- column벡터의 크기가 6인 a배열의 도착값으로 6을 입력하면 5번 인덱스를 의미

In [22]:
a[:,3:6]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [23]:
a[:,2:-1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

- `-1`은 마지막 인덱스를 의미

In [24]:
a[:,0:3:2]

array([[1, 3],
       [7, 9]])

##### 배열 붙이기
- 배열들의 크기에 주의

In [25]:
a = np.array([[1,2,3],[4,5,6]]) # (2,3) 크기의 행렬 a 선언
b = np.array([[7,8,9],[10,11,12]]) # (2,3) 크기의 행렬 b 선언
print(a)
print("\n",b)

[[1 2 3]
 [4 5 6]]

 [[ 7  8  9]
 [10 11 12]]


- `r_`는 기존 배열에 추가되는 배열을 마지막 row 아래에 붙임

In [26]:
np.r_[a,b] # row 를 추가

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

- `r_`과 같은 함수로 `concatenate((배열1,배열2), axiz=0)`를 사용 할 수 있음
- 단, 배열1과 배열2의 차원은 같아야 함

In [27]:
np.concatenate((a,b), axis=0) # 0은 row 를 의미함

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

- `c_`는 기존 배열에 추가되는 배열을 마지막 column의 오른쪽에 붙임

In [28]:
np.c_[a,b] # column 을 추가

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- `c_`와 같은 함수로 `concatenate((배열1,배열2), axis=1)`를 사용할 수 있음
- 단, 배열1과 배열2의 차원은 같아야 함

In [29]:
np.concatenate((a,b), axis=1) # 1은 column 을 의미함

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 5. 배열 연산
- numpy 배열 연산은 기본적인 연산 기호(+,-,*)에 맞게 연산
- 단, 벡터의 inner product나 행렬곱과 같은 특수한 연산은 특정 함수를 사용하여 수행

In [30]:
# 배열 덧셈
a = np.array([[1, 2, 3], [3, 2, 5]])
b = np.array([[-1, 3, 5], [1, 4, 2]])
a+b

array([[0, 5, 8],
       [4, 6, 7]])

In [31]:
# 배열 뺄셈
a-b

array([[ 2, -1, -2],
       [ 2, -2,  3]])

In [32]:
# * 연산은 각 성분끼리 곱한 형태를 출력
a*b

array([[-1,  6, 15],
       [ 3,  8, 10]])

In [33]:
# / 연산은 각 성분끼리 나눈 형태를 출력
a/b 
# 각 원소의 형태가 정수형이므로, 나눗셈 연산에서 자리 버림 발생

array([[-1.        ,  0.66666667,  0.6       ],
       [ 3.        ,  0.5       ,  2.5       ]])


### 퀴즈
Q. 배열 a,b를 합쳐서 배열 c를 만드는 코드로 알맞은 것을 고르세요.
물음표에 들어갈 코드로 알맞은 것을 고르세요
```python
import numpy as np

a = np.array([[1,2],[2,3]])
b = np.array([[1,2]])

c = ?
print(c)
```
결과 창
```
[[ 1, 2]
[2, 3]
[1, 2]]
```

- [X] np.r_[a,b]
- [ ] np.c_[a,b.reshape((-1,1))]
- [ ] a+b
- [ ] np.concatenate((a,b.reshape((-1,1)), axis=1)

퀴즈 해설 보기
- 결과 창의 배열이 나오기 위해서는 `a`배열에 `b`배열의 row를 아래로 추가하는 `np.r_[a,b]`를 사용해야 함
- 정답 1번을 제외한 나머지 결과는 다음과 같음
**2, 4번**
```
[[1 2 1]
 [2 3 2]]
```
- `b`배열을 column 벡터로 변환하여 오른쪽에 추가한 형태
**3번**
```
[[2 4]
 [3 5]]
```


In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/Github/